In [1]:
import numpy as np
import os
import json

In [2]:
from filtool_script import FiltoolExec

In [3]:
fil_exec = FiltoolExec('/home/rsenzel/Code/inception/dev_injector/fb/controlfb2_uhf.fil', 'mmgps_search.json', 'test_dir', 1)

In [177]:
def slices(csv):
    for value in csv.split(","):
        if ":" not in value:
            yield float(value)
        else:
            x = value.split(":")
            start = float(x[0])
            end = float(x[1])
            if len(x) > 2:
                step = float(x[2])
            else:
                step = 1
            for subvalue in np.arange(start, end, step):
                yield subvalue

In [179]:
ddplan = fil_exec.create_DDplan()
for dm_range in ddplan:
    dm_csv = f"{dm_range.low_dm}:{dm_range.high_dm}:{dm_range.dm_step}"
    dm_list = sorted(list(set(list(slices(dm_csv)))))
    np.savetxt(f'outfile_{dm_range.tscrunch}.txt', dm_list, fmt='%.3f')

In [191]:
with open("outfile_8.0.txt", "r") as file:
    numbers = np.array([float(line.strip()) for line in file])

with open("xml_files/dm_list_t8.ascii", "r") as file:
    numbers1 = np.array([float(line.strip()) for line in file])

np.sum(numbers-numbers1)

np.float64(0.0)

In [216]:
dm_trials_list = []
tscrunch_list = []
ddplan = list(fil_exec.create_DDplan())
for i, dm_range in enumerate(ddplan):
    n_trial = int(round((ddplan[i].high_dm-ddplan[i].low_dm)/ddplan[i].dm_step))
    n_trial, endpoint = (n_trial + 1, True) if (i == len(ddplan)-1) else (n_trial, False)

    dm_list_i = np.linspace(dm_range.low_dm, dm_range.high_dm, n_trial, endpoint=endpoint)
    dm_trials_list.append(dm_list_i)


In [217]:
i=2


In [218]:
dm_trials_list

[array([0.0000e+00, 3.0000e-02, 6.0000e-02, ..., 1.0371e+02, 1.0374e+02,
        1.0377e+02]),
 array([103.8 , 103.85, 103.9 , ..., 167.15, 167.2 , 167.25]),
 array([167.3, 167.4, 167.5, ..., 318.2, 318.3, 318.4]),
 array([318.5, 318.7, 318.9, 319.1, 319.3, 319.5, 319.7, 319.9, 320.1,
        320.3, 320.5, 320.7, 320.9, 321.1, 321.3, 321.5, 321.7, 321.9,
        322.1, 322.3, 322.5, 322.7, 322.9, 323.1, 323.3, 323.5, 323.7,
        323.9, 324.1, 324.3, 324.5, 324.7, 324.9, 325.1, 325.3, 325.5,
        325.7, 325.9, 326.1, 326.3, 326.5, 326.7, 326.9, 327.1, 327.3,
        327.5, 327.7, 327.9, 328.1, 328.3, 328.5, 328.7, 328.9, 329.1,
        329.3, 329.5, 329.7, 329.9, 330.1, 330.3, 330.5, 330.7, 330.9,
        331.1, 331.3, 331.5, 331.7, 331.9, 332.1, 332.3, 332.5, 332.7,
        332.9, 333.1, 333.3, 333.5, 333.7, 333.9, 334.1, 334.3, 334.5,
        334.7, 334.9, 335.1, 335.3, 335.5, 335.7, 335.9, 336.1, 336.3,
        336.5, 336.7, 336.9, 337.1, 337.3, 337.5, 337.7, 337.9, 338.1,
    

In [ ]:
DM_values = [pulsar['DM'] for pulsar in self.inj_report['pulsars']]
DD_plan = self.create_DDplan()

dm_trials_list = []
tscrunch_list = []
for i, dm_range in enumerate(DD_plan):
    n_trial = int((dm_range.high_dm-dm_range.low_dm)/dm_range.dm_step)
    n_trial, endpoint = (n_trial + 1, True) if (i == len(DD_plan)-1) else (n_trial, False)

    dm_list_i = np.linspace(dm_range.low_dm, dm_range.high_dm, n_trial, endpoint=endpoint)
    tscrunch_i = np.ones_like(dm_list_i) * dm_range.tscrunch

    dm_trials_list.append(dm_list_i)
    tscrunch_list.append(tscrunch_i)

dm_trials_arr = np.concatenate(dm_trials_list)
tscrunch_arr = np.concatenate(tscrunch_list)

dm_search_values = []
for DM_i in DM_values:
    dm_nearest, tscrunch_nearest = self.find_n_nearest(dm_trials_arr, tscrunch_arr, DM_i, self.n_nearest)
    dm_search_values.append(dm_nearest[np.where(tscrunch_nearest == self.tscrunch)])

dm_search_arr = np.concatenate(dm_search_values)
dm_search_arr = np.unique(dm_search_arr)

outfile = os.path.join(self.out, f"dm_list_t{int(self.tscrunch)}.ascii")
np.savetxt(outfile, dm_search_arr, fmt='%.3f')
return outfile

In [5]:
fil_exec.processing_args

{'rfi_flags': 'kadaneF 8 4 zdot',
 'temp_filesystem': '/beegfs/',
 'fscrunch': 1,
 'snr_threshold': 8.0,
 'nharmonics': '4',
 'fft_length': 4194304,
 'start_accel': -105.0,
 'end_accel': 105.0,
 'accel_tol': 1.11,
 'candidate_limit': 1000,
 'ddplan': ' 0.000 103.800 0.03 1 3460 0.7544\r\n 103.800 167.300 0.05 2 1270 0.1384\r\n 167.300 318.500 0.10 4 1512 0.08242\r\n 318.500 500.100 0.20 8 908 0.02475',
 'overrides': 'both',
 'birdie_list': '1000.00:0.05,1500.00:0.05,1300.00:0.05',
 'channel_mask': '932.00:961.00',
 'ram_limit': 24.0}

In [6]:
import xml.etree.ElementTree as ET
import json

In [7]:
with open('/home/rsenzel/Code/inception/offline_injector_nextflow/xml_files/injection_report_inj_000001.json', 'r') as file:
    pars = json.load(file)

psr = pars['pulsars']

In [8]:
def xml_to_dict(element):
    # Convert element attributes and text to a dictionary
    data = {element.tag: {} if element.attrib else None}
    children = list(element)
    
    # Process each child
    if children:
        dd = {}
        for dc in map(xml_to_dict, children):
            for k, v in dc.items():
                if k in dd:
                    if not isinstance(dd[k], list):
                        dd[k] = [dd[k]]
                    dd[k].append(v)
                else:
                    dd[k] = v
        data = {element.tag: dd}
    if element.attrib:
        data[element.tag].update(('@' + k, v) for k, v in element.attrib.items())
    if element.text:
        text = element.text.strip()
        if children or element.attrib:
            if text:
                data[element.tag]['#text'] = text
        else:
            data[element.tag] = text
    return data

In [9]:
con1 = xml_to_dict(ET.parse('xml_files/control_1.xml').getroot())['peasoup_search']['candidates']['candidate']
con2 = xml_to_dict(ET.parse('xml_files/control_2.xml').getroot())['peasoup_search']['candidates']['candidate']
con3 = xml_to_dict(ET.parse('xml_files/control_3.xml').getroot())['peasoup_search']['candidates']['candidate']
con4 = xml_to_dict(ET.parse('xml_files/control_4.xml').getroot())['peasoup_search']['candidates']['candidate']

inj1 = xml_to_dict(ET.parse('xml_files/inj_1.xml').getroot())['peasoup_search']['candidates']['candidate']
inj2 = xml_to_dict(ET.parse('xml_files/inj_2.xml').getroot())['peasoup_search']['candidates']['candidate']
inj3 = xml_to_dict(ET.parse('xml_files/inj_3.xml').getroot())['peasoup_search']['candidates']['candidate']
inj4 = xml_to_dict(ET.parse('xml_files/inj_4.xml').getroot())['peasoup_search']['candidates']['candidate']

orig1 = xml_to_dict(ET.parse('xml_files/orig_1.xml').getroot())['peasoup_search']['candidates']['candidate']
orig2 = xml_to_dict(ET.parse('xml_files/orig_2.xml').getroot())['peasoup_search']['candidates']['candidate']
orig3 = xml_to_dict(ET.parse('xml_files/orig_3.xml').getroot())['peasoup_search']['candidates']['candidate']
orig4 = xml_to_dict(ET.parse('xml_files/orig_4.xml').getroot())['peasoup_search']['candidates']['candidate']

# nm1 = xml_to_dict(ET.parse('xml_files/no_merge_1.xml').getroot())['peasoup_search']['candidates']['candidate']
# nm2 = xml_to_dict(ET.parse('xml_files/no_merge_2.xml').getroot())['peasoup_search']['candidates']['candidate']
# nm3 = xml_to_dict(ET.parse('xml_files/no_merge_3.xml').getroot())['peasoup_search']['candidates']['candidate']
# nm4 = xml_to_dict(ET.parse('xml_files/no_merge_4.xml').getroot())['peasoup_search']['candidates']['candidate']

con = [*con1, *con2, *con3, *con4]
inj = [*inj1, *inj2, *inj3, *inj4]
orig = [*orig1, *orig2, *orig3, *orig4]
# nm = [*nm1, *nm2, *nm3, *nm4]

len(con), len(orig),  len(inj) #len(nm),

(806, 803, 804)

In [10]:
[len(con1), len(con2), len(con3), len(con4)], [len(orig1), len(orig2), len(orig3), len(orig4)],  [len(inj1), len(inj2), len(inj3), len(inj4)]

([520, 150, 113, 23], [525, 151, 104, 23], [514, 145, 117, 28])

In [18]:
sum(np.array([float(ci['snr']) for ci in con4])- np.array([float(ci['snr']) for ci in orig4]))

np.float64(0.0)

In [ ]:
class CandidateXMLMatcher:
    def __init__(self, injected_pulsars, injected_xml, original_xml):
        self.injected_xml = self.get_cands(injected_xml)
        self.original_xml = self.get_cands(original_xml)
        self.psr = self.get_pulsars(injected_pulsars)

    def get_cands(self, xml):
        return self.xml_to_dict(ET.parse(xml).getroot())['peasoup_search']['candidates']['candidate']
    
    def get_pulsars(self, psr_file):
        with open(psr_file, 'r') as file:
            pars = json.load(file)
        return pars['pulsars']
    
    @staticmethod
    def xml_to_dict(element):
        data = {element.tag: {} if element.attrib else None}
        children = list(element)
        
        if children:
            dd = {}
            for dc in map(xml_to_dict, children):
                for k, v in dc.items():
                    if k in dd:
                        if not isinstance(dd[k], list):
                            dd[k] = [dd[k]]
                        dd[k].append(v)
                    else:
                        dd[k] = v
            data = {element.tag: dd}
        if element.attrib:
            data[element.tag].update(('@' + k, v) for k, v in element.attrib.items())
        if element.text:
            text = element.text.strip()
            if children or element.attrib:
                if text:
                    data[element.tag]['#text'] = text
            else:
                data[element.tag] = text
        return data

In [134]:
def condition(key, tol, cand1, cand2):
    lower = (float(cand1[key]) >= float(cand2[key])*(1-tol)) 
    upper = (float(cand1[key]) <= float(cand2[key])*(1+tol)) 
    return lower and upper

def get_diffs(inj_cand, orig_cand):
    period_diff = float(inj_cand['period'])-float(orig_cand['period'])
    dm_diff = float(inj_cand['dm'])-float(orig_cand['dm'])
    acc_diff = float(inj_cand['acc'])-float(orig_cand['acc'])
    snr_diff = float(inj_cand['snr'])-float(orig_cand['snr'])
    return period_diff, dm_diff, acc_diff, snr_diff

def get_cand_match(original, injected, tol):
    cand_match = []
    for i, inj_cand in enumerate(injected):
        for j, orig_cand in enumerate(original):
            condition1 = condition('period', tol, inj_cand, orig_cand)
            condition2 = condition('dm', tol, inj_cand, orig_cand)
            condition3 = condition('acc', tol, inj_cand, orig_cand)
            if condition1 and condition2 and condition3:
                cand_match.append([i, j, *get_diffs(inj_cand, orig_cand)])
                break
    return np.array(cand_match)

def remove_cands(cands1, cands2, cand_match):
    cands1c = cands1.copy()
    cands2c = cands2.copy()

    ind1 = cand_match.T[0].astype(int)
    ind2 = cand_match.T[1].astype(int)
    for index in sorted(ind1, reverse=True):
        del cands1c[index]
    for index in sorted(ind2, reverse=True):
        del cands2c[index]
    return cands1c, cands2c

In [135]:
cand_match1 = get_cand_match(orig1, con1, tol=0)
cand_match2 = get_cand_match(orig2, con2, tol=0)
cand_match3 = get_cand_match(orig3, con3, tol=0)
cand_match4 = get_cand_match(orig4, con4, tol=0)
[[len(cand_match1), len(con1), len(orig1)],
 [len(cand_match2), len(con2), len(orig2)],
 [len(cand_match3), len(con3), len(orig3)],
 [len(cand_match4), len(con4), len(orig4)]]

[[393, 520, 525], [145, 150, 151], [6, 113, 104], [23, 23, 23]]

In [140]:
nc1, no1 = remove_cands(con1, orig1, cand_match1)
nc2, no2 = remove_cands(con2, orig2, cand_match2)
nc3, no3 = remove_cands(con3, orig3, cand_match3)
nc4, no4 = remove_cands(con4, orig4, cand_match4)

In [169]:
cm1 = get_cand_match(no1, nc1, tol=0.01)
cm2 = get_cand_match(no2, nc2, tol=0.01)
cm3 = get_cand_match(no3, nc3, tol=0.01)
cm4 = get_cand_match(no4, nc4, tol=0.01)
len(cm1), len(cm2), len(cm3), len(cm4)

(6, 0, 6, 0)

In [168]:
cm1 = get_cand_match(no1, nc1, tol=0.05)
cm2 = get_cand_match(no2, nc2, tol=0.05)
cm3 = get_cand_match(no3, nc3, tol=0.05)
cm4 = get_cand_match(no4, nc4, tol=0.05)
len(cm1), len(cm2), len(cm3), len(cm4)

(6, 0, 8, 0)

In [170]:
cm1 = get_cand_match(no1, nc1, tol=0.1)
cm2 = get_cand_match(no2, nc2, tol=0.1)
cm3 = get_cand_match(no3, nc3, tol=0.1)
cm4 = get_cand_match(no4, nc4, tol=0.1)
len(cm1), len(cm2), len(cm3), len(cm4)

(9, 0, 16, 0)

In [112]:
cand_match4

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  0.,  0.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0.],
       [ 4.,  4.,  0.,  0.,  0.,  0.],
       [ 5.,  5.,  0.,  0.,  0.,  0.],
       [ 6.,  6.,  0.,  0.,  0.,  0.],
       [ 7.,  7.,  0.,  0.,  0.,  0.],
       [ 8.,  8.,  0.,  0.,  0.,  0.],
       [ 9.,  9.,  0.,  0.,  0.,  0.],
       [10., 10.,  0.,  0.,  0.,  0.],
       [11., 11.,  0.,  0.,  0.,  0.],
       [12., 12.,  0.,  0.,  0.,  0.],
       [13., 13.,  0.,  0.,  0.,  0.],
       [14., 14.,  0.,  0.,  0.,  0.],
       [15., 15.,  0.,  0.,  0.,  0.],
       [16., 16.,  0.,  0.,  0.,  0.],
       [17., 17.,  0.,  0.,  0.,  0.],
       [18., 18.,  0.,  0.,  0.,  0.],
       [19., 19.,  0.,  0.,  0.,  0.],
       [20., 20.,  0.,  0.,  0.,  0.],
       [21., 21.,  0.,  0.,  0.,  0.],
       [22., 22.,  0.,  0.,  0.,  0.]])

In [62]:
len(orig1), len(con1), len(orig1)-394, len(con1)-394

(525, 520, 131, 126)

In [35]:
inj_p0 = [psr_i['PX'][0] for psr_i in psr]
inj_dm = [psr_i['DM'] for psr_i in psr]
inj_snr = [round(psr_i['SNR'], 5) for psr_i in psr]
inj_bin = [psr_i['binary_period'] for psr_i in psr]
list(zip(inj_p0, inj_dm, inj_snr, inj_bin))

[(2.119481126264242, 89.38349026324208, 13.45509, None),
 (0.02033142050659543, 334.9673500263703, 29.33122, 11513.124734778808),
 (0.006310689271586747, 95.64797204949794, 13.86007, 6741.748742748116),
 (0.029860443236433526, 497.61791041498606, 39.84601, 14755.933509768929),
 (0.003299254582649314, 44.24589718660036, 10.53711, 5716.9314963774705),
 (0.005696684430317391, 85.16754458645202, 13.18255, 6532.797589665021),
 (0.021825437688184793, 360.46867778108526, 30.97979, 12021.551691435498),
 (0.01423765451349229, 230.95306841995458, 22.60707, 9439.363511259613),
 (0.0015585260986010706, 14.533462717501033, 8.6163, 5124.546551668371),
 (0.02690584124480148, 447.185910902646, 36.58576, 13750.456921381103)]

In [21]:
con2

[{'period': '0.742255241200427',
  'opt_period': '0',
  'dm': '166.550003051758',
  'acc': '-30.5183792114258',
  'nh': '3',
  'snr': '48.8953666687012',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '13129',
  'byte_offset': '0',
  '@id': '0'},
 {'period': '0.247448702068106',
  'opt_period': '0',
  'dm': '167',
  'acc': '0',
  'nh': '2',
  'snr': '30.4157447814941',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '5573',
  'byte_offset': '315124',
  '@id': '1'},
 {'period': '0.741982779604984',
  'opt_period': '0',
  'dm': '164.100006103516',
  'acc': '-105',
  'nh': '1',
  'snr': '26.3965396881104',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '20132',
  'byte_offset': '448904',
  '@id': '2'},
 {'period': '2.22656141962996',
  'opt_period': '0',

In [23]:
orig2

[{'period': '0.742255241200427',
  'opt_period': '0',
  'dm': '166.550003051758',
  'acc': '-30.5183792114258',
  'nh': '3',
  'snr': '48.8839225769043',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '13139',
  'byte_offset': '0',
  '@id': '0'},
 {'period': '0.247448702068106',
  'opt_period': '0',
  'dm': '166.850006103516',
  'acc': '6.89961242675781',
  'nh': '2',
  'snr': '30.4072418212891',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '5579',
  'byte_offset': '315364',
  '@id': '1'},
 {'period': '0.741982779604984',
  'opt_period': '0',
  'dm': '163.899993896484',
  'acc': '-68.2803802490234',
  'nh': '1',
  'snr': '26.4004306793213',
  'folded_snr': '0',
  'is_adjacent': '1',
  'is_physical': '1',
  'ddm_count_ratio': '1',
  'ddm_snr_ratio': '1',
  'nassoc': '20150',
  'byte_offset': '449288',
  '@id': '2'},
 {'period':

In [43]:
def get_lens(cands):
    n_cands = []
    for i in range(len(inj_p0)):
        tol=0.05
        dm_tol = 0.05
        cand0 = []
        for ci in cands:
            cond1 = (float(ci['period']) > inj_p0[i]*(1-tol)) & (float(ci['period']) < inj_p0[i]*(1+tol))
            cond2 = (float(ci['dm']) > inj_dm[i]*(1-dm_tol)) & (float(ci['dm']) < inj_dm[i]*(1+dm_tol))
            if cond1 and cond2:
                cand0.append(ci)
        n_cands.append(len(cand0))
    return n_cands

In [44]:
get_lens(con), get_lens(orig), get_lens(inj) # get_lens(nm)

([0, 0, 0, 0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 1, 3, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 2, 1, 2, 0, 2])

In [132]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [104]:
con_csv = pd.read_csv('xml_files/con_cands_to_fold.csv')
inj_csv = pd.read_csv('xml_files/inj_cands_to_fold.csv')
len(con_csv), len(inj_csv)

(23214, 23219)

In [24]:
import re

In [25]:
expr = "/tmp/rsenzel/MMGPS_U_0018_cfbf00125_data_000001_merged.fil"
match = re.search(r'[ci]fbf\d{5}', expr).group()
match

'cfbf00125'

In [26]:
def generate_pulsarX_cand_file(
        tmp_dir,
        beam_name,
        cand_mod_periods,
        cand_dms,
        cand_accs,
        cand_snrs):

    cand_file_path = f'{tmp_dir}/{beam_name}_cands.candfile' 
    with open(cand_file_path, 'w') as f:
        f.write("#id DM accel F0 F1 S/N\n")
        for i in range(len(cand_mod_periods)):
            f.write(
                "%d %f %f %f 0 %f\n" %
                (i,
                 cand_dms[i],
                    cand_accs[i],
                    1.0 /
                    cand_mod_periods[i],
                    cand_snrs[i]))
        f.close()

    return cand_file_path

In [28]:
int(123123 // 4.3)

28633

In [ ]:
mod_periods = []
pdots = []
for i in range(len(cand_periods)):
    Pdot = a_to_pdot(cand_periods[i], cand_accs[i])
    mod_periods.append(
        period_modified(
            cand_periods[i],
            Pdot,
            no_of_samples,
            tsamp,
            fft_size))
    pdots.append(Pdot)

cand_mod_periods = np.asarray(mod_periods, dtype=float)

In [13]:
tmp_dir="test_dir"
beam_name = match


'-i 258'

In [140]:
cmask = "856.0:863.94140625"
zap_string = ""
if cmask is not None:
    cmask = cmask.strip()
    if cmask:
        zap_string = " ".join(["--rfi zap {} {}".format(*i.split(":")) for i in cmask.split(",")])

In [142]:
cmask = cmask.strip()
cmask

'856.0:863.94140625'

In [105]:
con_csv = con_csv.reindex()
inj_csv = inj_csv.reindex()

In [107]:
locs = []
offset = 0
for i in range(len(con_csv)):
    con_i = con_csv.iloc[i+offset]
    inj_i = inj_csv.iloc[i]
    if (round(con_i['period'], 3) == round(inj_i['period'], 3)):
        pass
    else:
        locs.append(i)
        offset -= 1

In [116]:
# locs

In [109]:
i=8
inj_csv.iloc[i]['period'], con_csv.iloc[i]['period'], inj_csv.iloc[i]['dm'], con_csv.iloc[i]['dm']

(np.float64(0.0130741628977736),
 np.float64(2.00214078447418),
 np.float64(211.22900390625),
 np.float64(391.299987792969))

In [112]:
inj_csv.head(35)

Unnamed: 0  level_0  index    period  opt_period          dm         acc  \
0            0        0     23  1.002560           0  383.700012 -105.000000   
1            1        2     31  2.003133           0  404.500000 -105.000000   
2            2        3     32  2.005120           0  413.299988   -4.956955   
3            3        4     34  0.667490           0  268.100006 -105.000000   
4            4        6     41  5.002874           0  404.500000 -105.000000   
5            5        7     50  1.427374           0  477.899994 -105.000000   
6            6        8     53  1.000575           0  198.199997 -105.000000   
7            7        9     57  2.001150           0  271.700012   19.580593   
8            8       10     62  0.013074           0  211.229004  -79.531494   
9            9       11     65  2.002141           0  391.299988  105.000000   
10          10       12     66  5.002874           0  245.100006  105.000000   
11          11       13     69  2.000159           0  383.700012 -105.000000   
12          12       14     72  0.667490           0  387.899994  105.000000   
13          13       15     75  4.996690           0  374.100006   34.507347   
14          14       17     83  0.400071           0  160.750000  -86.949280   
15          16       19     90  3.978663           0   43.470001   90.932594   
16          18       21     93  4.996690           0  133.199997   95.009163   
17          19       22     94  3.338003           0  271.700012  -11.564554   
18          20       23     95  2.000159           0  161.699997  105.000000   
19          21       24     97  4.999780           0  212.300003   48.397907   
20          22       25    100  4.999780           0  140.649994 -105.000000   
21          24       27    104  4.996690           0  168.300003   46.650726   
22          25       28    107  0.400071           0  172.600006 -105.000000   
23          27       31    111  2.000159           0  169.699997  -17.863035   
24          28       32    113  0.079989           0    8.280000  -83.227112   
25          29       33    114  1.309042           0  477.899994  105.000000   
26          30       34    116  4.996690           0  103.470001  -93.588089   
27          31       36    122  3.978663           0   28.620001 -100.370972   
28          33       38    126  0.002096           0  407.899994    0.253967   
29          34       39    128  5.002874           0   87.449997   81.716049   
30          37       42    133  0.018360           0  301.688995  103.542572   
31          38       43    134  0.001940           0  436.899994    0.179378   
32          39       44    135  0.222203           0   96.209999   23.281223   
33          40       45    136  0.002081           0  442.899994    0.000000   
34          41       46    138  0.666610           0  262.500000  105.000000   

    nh        snr  folded_snr  ...    src_raj    src_rajd   src_dej  \
0    0  27.812326           0  ...  121848.88  184.703667 -595533.5   
1    2  23.437431           0  ...  121848.88  184.703667 -595533.5   
2    1  23.043993           0  ...  121848.88  184.703667 -595533.5   
3    0  22.241913           0  ...  121848.88  184.703667 -595533.5   
4    3  20.534908           0  ...  121848.88  184.703667 -595533.5   
5    0  18.481922           0  ...  121848.88  184.703667 -595533.5   
6    1  18.114378           0  ...  121848.88  184.703667 -595533.5   
7    2  17.628910           0  ...  121848.88  184.703667 -595533.5   
8    1  17.233582           0  ...  122053.45  185.222708 -594906.9   
9    3  16.943661           0  ...  121848.88  184.703667 -595533.5   
10   3  16.851202           0  ...  121848.88  184.703667 -595533.5   
11   3  16.539663           0  ...  121848.88  184.703667 -595533.5   
12   0  16.334745           0  ...  121848.88  184.703667 -595533.5   
13   3  16.077702           0  ...  121848.88  184.703667 -595533.5   
14   0  15.815430           0  ...  121848.88  184.703667 

In [113]:
con_csv.head(35)

Unnamed: 0  level_0  index    period  opt_period          dm         acc  \
0            0        0     23  1.002560           0  383.700012 -105.000000   
1            1        2     31  2.003133           0  404.500000 -105.000000   
2            2        3     32  2.005120           0  413.299988   -4.956955   
3            3        4     34  0.667490           0  268.100006 -105.000000   
4            4        6     41  5.002874           0  404.500000 -105.000000   
5            5        7     50  1.427374           0  477.899994 -105.000000   
6            6        8     53  1.000575           0  198.199997 -105.000000   
7            7        9     57  2.001150           0  271.700012   19.580593   
8            8       10     64  2.002141           0  391.299988  105.000000   
9            9       11     65  5.002874           0  245.100006  105.000000   
10          10       12     68  2.000159           0  383.700012 -105.000000   
11          11       13     71  0.667490           0  387.899994  105.000000   
12          12       14     74  4.996690           0  374.100006   34.507347   
13          13       16     82  0.400071           0  160.750000  -86.949280   
14          15       18     89  3.978663           0   43.470001   90.932594   
15          17       20     92  4.996690           0  133.199997   95.009163   
16          18       21     93  3.338003           0  271.700012  -11.564554   
17          19       22     94  2.000159           0  161.699997  105.000000   
18          20       23     96  4.999780           0  212.300003   48.397907   
19          21       24     99  4.999780           0  140.649994 -105.000000   
20          23       26    103  4.996690           0  168.300003   46.650726   
21          24       27    106  0.400071           0  172.600006 -105.000000   
22          26       30    110  2.000159           0  169.699997  -17.863035   
23          27       31    112  0.079989           0    8.280000  -83.227112   
24          28       32    113  1.309042           0  477.899994  105.000000   
25          29       33    115  4.996690           0  103.470001  -93.588089   
26          30       36    122  3.978663           0   28.620001 -100.370972   
27          32       39    128  5.002874           0   87.449997   81.716049   
28          35       42    133  0.222203           0   96.209999   23.281223   
29          36       43    134  0.002096           0  407.899994    0.253967   
30          37       45    137  0.666610           0  262.500000  105.000000   
31          38       46    139  0.002137           0  393.500000    0.000000   
32          39       47    140  0.005033           0  386.700012   -3.056660   
33          40       48    141  0.002081           0  442.899994    0.000000   
34          42       50    145  0.002139           0  329.100006    0.000000   

    nh        snr  folded_snr  ...    src_raj    src_rajd   src_dej  \
0    0  27.812326           0  ...  121848.88  184.703667 -595533.5   
1    2  23.437431           0  ...  121848.88  184.703667 -595533.5   
2    1  23.043993           0  ...  121848.88  184.703667 -595533.5   
3    0  22.241913           0  ...  121848.88  184.703667 -595533.5   
4    3  20.534908           0  ...  121848.88  184.703667 -595533.5   
5    0  18.481922           0  ...  121848.88  184.703667 -595533.5   
6    1  18.114378           0  ...  121848.88  184.703667 -595533.5   
7    2  17.628910           0  ...  121848.88  184.703667 -595533.5   
8    3  16.943661           0  ...  121848.88  184.703667 -595533.5   
9    3  16.851202           0  ...  121848.88  184.703667 -595533.5   
10   3  16.539663           0  ...  121848.88  184.703667 -595533.5   
11   0  16.334745           0  ...  121848.88  184.703667 -595533.5   
12   3  16.077702           0  ...  121848.88  184.703667 -595533.5   
13   0  15.815430           0  ...  121848.88  184.703667 -595533.5   
14   0  15.125060           0  ...  122108.04  185.283500 

In [ ]:
# 28	35	42	133	0.222203	0	96.209999	23.281223	0	12.724810

In [72]:
inj_csv.iloc[8] #0.013088825061494773, 211.3437381186177, 21.33939, 9039.358514819074

level_0                                                                10
index                                                                  62
period                                                           0.013074
opt_period                                                              0
dm                                                             211.229004
acc                                                            -79.531494
nh                                                                      1
snr                                                             17.233582
folded_snr                                                              0
is_adjacent                                                             1
is_physical                                                             1
ddm_count_ratio                                                  0.951923
ddm_snr_ratio                                                    0.966693
nassoc                                

In [13]:
ddplan = list(fil_exec.create_DDplan())
filplan = fil_exec.create_filplan(ddplan)

In [14]:
ddplan = fil_exec.create_DDplan()

In [26]:
np.unique(np.random.randint(0, 11, size=10000))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr = np.array(['abs', 'rty', 'fer', 'fre'])

with open("output.txt", "w") as file:
    # Add a newline character to each string and write to file
    file.writelines(line + "\n" for line in arr)

In [31]:
from scipy.stats import truncnorm

In [34]:
trvs = truncnorm(a=10, b=20, loc=25, scale=5).rvs

In [42]:
trvs(random_state=0)

np.float64(75.39255995729471)

In [43]:
2**23

8388608

In [11]:
f'overview_dm_0.000000_103.800000.xml'

'overview_dm_0.000000_103.800000.xml'

In [12]:
xml_file_names = [f'overview_dm_{dm_range.low_dm:.6f}_{dm_range.high_dm:.6f}.xml' for dm_range in ddplan]
xml_file_names

['overview_dm_0.000000_103.800000.xml',
 'overview_dm_103.800000_167.300000.xml',
 'overview_dm_167.300000_318.500000.xml',
 'overview_dm_318.500000_500.100000.xml']

In [6]:
for i in ddplan:
    print(i)

DMRange(low_dm=0.0, high_dm=517.8, dm_step=0.3, tscrunch=1.0)
DMRange(low_dm=517.8, high_dm=834.8, dm_step=0.5, tscrunch=2.0)
DMRange(low_dm=834.8, high_dm=1589.8, dm_step=1.0, tscrunch=4.0)
DMRange(low_dm=1589.8, high_dm=3001.8, dm_step=2.0, tscrunch=8.0)


In [45]:
dm_range = np.linspace(ddplan[0].low_dm, ddplan[0].high_dm, int((ddplan[0].high_dm-ddplan[0].low_dm)/ddplan[0].dm_step), endpoint=False)
dm1 = np.linspace(ddplan[1].low_dm, ddplan[1].high_dm, int((ddplan[1].high_dm-ddplan[1].low_dm)/ddplan[1].dm_step), endpoint=False)

In [82]:
dm_trials_list = []
tscrunch_list = []
for i, dm_range in enumerate(ddplan):
    n_trial = int((dm_range.high_dm-dm_range.low_dm)/dm_range.dm_step)
    n_trial, endpoint = (n_trial + 1, True) if i == len(ddplan)-1 else (n_trial, False)
    dm_list_i = np.linspace(dm_range.low_dm, dm_range.high_dm, n_trial, endpoint=endpoint)
    tscrunch = np.ones_like(dm_list_i) * dm_range.tscrunch
    dm_trials_list.append(dm_list_i)
    tscrunch_list.append(tscrunch)

In [83]:
dm_trials = np.concat(dm_trials_list)
tscrunch = np.concat(tscrunch_list)
tscrunch

array([1., 1., 1., ..., 8., 8., 8.])

In [66]:
def find_n_nearest(dm_arr, tscrunch_arr, target, n):
    nearest_indices = np.argsort(np.abs(dm_arr - target))[:n]
    dm_values = dm_arr[nearest_indices]
    tscrunch_values = tscrunch_arr[nearest_indices]
    return dm_values, tscrunch_values

In [71]:
a, b = find_n_nearest(dm_trials, tscrunch, 517.7, 5)
a, b

(array([517.8, 517.5, 517.2, 518.3, 516.9]), array([2., 1., 1., 2., 1.]))

In [81]:
np.where(np.array([dm_range.tscrunch for dm_range in ddplan] )== 2)[0][0]

np.int64(1)

In [73]:
a[np.where(b == 1)]

array([517.5, 517.2, 516.9])

In [50]:
my_dms = np.random.uniform(50, 1500, size=10)
nearest = 5
dm_search = np.zeros((len(my_dms), nearest))
my_dms, dm_search

(array([1072.13331736, 1374.67901752, 1121.25312234, 1487.44617915,
        1061.48080809, 1298.42985136, 1143.93419058,  585.98544057,
         226.25915701,  530.1386847 ]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))